elimination/Elimination/Elimination/Controllers/Api/GamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using Elimination.Models;
using Elimination.Models.Api;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity;

namespace Elimination.Controllers.Api
{
    public class GamesController : ApiController
    {
        private EliminationDBContext db = new EliminationDBContext();

        // GET api/Games
        public IQueryable<Game> GetGames()
        {
            return db.Games;
        }


        // GET: api/Games/5
        [HttpGet]
        [Authorize]
        [ResponseType(typeof(JsonGame))]
        public async Task<IHttpActionResult> GetGame(int id)
        {
            Game game = await db.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }

            return Ok(JsonBuilder.BuildGame(game));
        }

        // GET: api/Games/5
        [HttpGet]
        [Authorize]
        [ResponseType(typeof(JsonGame))]
        public async Task<IHttpActionResult> GetGameList(string ids)
        {
            string[] idArray = null;

            try
            {
                idArray = ids.Split(',').ToArray();
            }
            catch (Exception e) { return NotFound(); }

            var games = await db.Games.Where(g => idArray.ToList().Contains(g.GameID.ToString())).ToListAsync();

            List<JsonGame> jsonGames = JsonBuilder.BuildGames(games);

            if (games == null)
            {
                return NotFound();
            }

            return Ok(jsonGames);
        }

        // GET: api/Games/5
        [HttpGet]
        [Authorize]
        [ResponseType(typeof(JsonGame))]
        public async Task<IHttpActionResult> GetAllGames()
        {
            var games = await db.Games.ToListAsync();

            List<JsonGame> jsonGames = JsonBuilder.BuildGames(games);

            if (games == null)
            {
                return NotFound();
            }

            return Ok(jsonGames);
        }

        // GET: api/Games/5
        [HttpGet]
        [Authorize]
        [ResponseType(typeof(JsonGame))]
        public async Task<IHttpActionResult> GetAllPlayers(int? id)
        {
            int gameID = id ?? -1;
            var game = await db.Games.FindAsync(gameID);

            List<JsonPlayer> jPlayers = JsonBuilder.BuildPlayers(game);

            if (game == null)
            {
                return NotFound();
            }

            return Ok(jPlayers);
        }

        [Authorize]
        [HttpPost]
        public async Task<IHttpActionResult> JoinGame(int id, LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                //get user id by matching email
                var tempPlayer =  db.AspNetUsers.Where(x => x.Email == model.Email).Select(x=>x.Id).ToList();

                var temp = tempPlayer[0];
                //make Player and set it to current user
                Player player = db.Players.Where(x => x.AuthUserID.Equals(temp)).FirstOrDefault();

                Game game = db.Games.FirstOrDefault(s => s.GameID == id);
                PlayersList pList = new PlayersList
                {
                    Game = game,
                    GameID = game.GameID,
                    Player = player,
                    PlayerID = player.PlayerID,
                    TargetCode = new Random().Next(9999)
                };
               
                    if (game != null)
                    {

                    var host = game.Host;
                    var joined = game.Players;
                   //if player already joined
                    if (joined.Any(x => x.PlayerID == player.PlayerID))   
                    {
                        return BadRequest("Already Joined");
                    }

                    // if player is host
                    if (host.Equals(player.PlayerID))
                    {
                        return BadRequest("You're the host!");
                    }
                    //add player to game Players list
                        game.PlayersLists.Add(pList);
                        game.AddPlayer(player);
                    }
                    db.SaveChanges();
                    return Ok("You've joined");
              
            }
            return BadRequest("Join failed");
        }



        // PUT: api/Games/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutGame(int id, Game game)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != game.GameID)
            {
                return BadRequest();
            }

            db.Entry(game).State = EntityState.Modified;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GameExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Games
        [Authorize]
        [ResponseType(typeof(Game))]
        public async Task<IHttpActionResult> PostGame(Game game)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Games.Add(game);
            await db.SaveChangesAsync();

            return CreatedAtRoute("DefaultApi", new { id = game.GameID }, game);
        }

        // DELETE: api/Games/5
        [Authorize]
        [ResponseType(typeof(Game))]
        public async Task<IHttpActionResult> DeleteGame(int id)
        {
            Game game = await db.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }

            db.Games.Remove(game);
            await db.SaveChangesAsync();

            return Ok(game);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool GameExists(int id)
        {
            return db.Games.Count(e => e.GameID == id) > 0;
        }
    }
}

elimination/Elimination/Elimination/Controllers/GamesController.cs
using Elimination.Models;
using Microsoft.AspNet.Identity;
using ServerNotifications.Web.Domain;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web.Mvc;
using Elimination.Domain.Twilio;
using Elimination.Models;
using Microsoft.AspNet.Identity;
using Microsoft.ProjectOxford.Face.Contract;
using ServerNotifications.Web.Domain;
using Twilio.Rest.Api.V2010.Account;
using Twilio.Types;

namespace Elimination.Controllers
{
    public class GamesController : Controller
    {
        private EliminationDBContext db = new EliminationDBContext();

        // GET: Games
        public ActionResult Index(string searchBy, string search, bool? inActive)
        {
            List<Game> games;
            bool tempInActive;

            if (inActive != null)
            {
                tempInActive = Convert.ToBoolean(inActive);
            }
            else
            {
                tempInActive = false;
            }

            if (tempInActive == false)
            {
                games = db.Games.Include(x => x.Player).ToList();
            }
            else //if( tempInActive == true)
            {
                games = db.Games.Where(x => x.Active == false).Include(x => x.Player).ToList();
            }
            if (searchBy == "Name")
            {
                return View(games.Where(x => x.Name.StartsWith(search) || search == null).ToList());
            }

            else if (searchBy == "location")
            {
                return View(games.Where(x => x.Location.StartsWith(search) || search == null).ToList());
            }
            else
            {
                return View(games.ToList());
            }
        }

        // GET: Games/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            int gameID = id ?? -1;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //the game that matched the id
            Game game = db.Games.Find(gameID);

            //current player id
            string currentp = User.Identity.GetUserId();

            // player element of current player id
            Player player = db.Players.Where(x => x.AuthUserID.Equals(currentp)).FirstOrDefault();
            ViewBag.playerID = player.PlayerID;

            if (game != null && player.AuthUserID.Equals(currentp) && game.Host == player.PlayerID)
            {
                ViewBag.Player = "Host";
            }
            else
            {
                //all players in game
                var joined = game.Players;

                // if already joined
                if (joined.Any(x => x.PlayerID == player.PlayerID))
                {
                    ViewBag.Player = "AlreadyJoined";
                }
                else //not yet joined 
                {
                    ViewBag.Player = "Join";
                }
            }
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details([Bind(Include = "GameID, PlayerID")]  int id)
        {

            string tempPlayer = User.Identity.GetUserId();
            //make Player and set it to current user
            Player player = db.Players.Where(x => x.AuthUserID.Equals(tempPlayer)).FirstOrDefault();

            Game game = db.Games.FirstOrDefault(s => s.GameID == id);
            PlayersList pList = new PlayersList
            {
                Game = game,
                GameID = game.GameID,
                Player = player,
                PlayerID = player.PlayerID,
                TargetCode = new Random().Next(9999)
            };

            if (ModelState.IsValid)
            {
                if (game != null)
                {
                    //add player to game Players list
                    game.PlayersLists.Add(pList);
                    game.AddPlayer(player);
                }
                db.SaveChanges();
                return RedirectToAction("Details/" + id);
            }
            return View(game);
        }

        // GET: Games/Details/5
        public ActionResult HostDetails(int? id)
        {
            int gameID = id ?? -1;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //the game that matched the id
            Game game = db.Games.Find(gameID);

            //current player id
            string currentp = User.Identity.GetUserId();

            // player element of current player id
            Player player = db.Players.Where(x => x.AuthUserID.Equals(currentp)).FirstOrDefault();

            ViewBag.playerID = player.PlayerID;

            if (game != null && player.AuthUserID.Equals(currentp) && game.Host == player.PlayerID)
            {
                ViewBag.Player = "Host";
            }
            else
            {
                return HttpNotFound();
            }

            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Games/Details
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult HostDetails([Bind(Include = "GameID, PlayerID")]  int id)
        {

            string tempPlayer = User.Identity.GetUserId();
            //make Player and set it to current user
            Player player = db.Players.Where(x => x.AuthUserID.Equals(tempPlayer)).FirstOrDefault();

            Game game = db.Games.FirstOrDefault(s => s.GameID == id);
            if (ModelState.IsValid)
            {
                if (game != null)
                {
                    game.AddPlayer(player);
                }
                db.SaveChanges();
                return RedirectToAction("Details/" + id);
            }
            return View(game);
        }

        // GET: Games/Create
        public ActionResult Create()
        {
            ViewBag.Host = new SelectList(db.Players, "PlayerID", "FirstName");
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GameID,Name,Host,Active,StartDate,EndDate,Location,LocationCenterLong,LocatoinCenterLat,LocationRadius")] Game game)
        {
            //get playerID so host can be set
            string tempPlayer = User.Identity.GetUserId();
            Player player = db.Players.Where(x => x.AuthUserID.Equals(tempPlayer)).FirstOrDefault();

            if (ModelState.IsValid)
            {
                game.Host = player.PlayerID;
                db.Games.Add(game);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Host = new SelectList(db.Players, "PlayerID", "FirstName", game.Host);
            return View(game);
        }

        // GET: Games/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }

            //prevents user editing other user's game
            string tempPlayer = User.Identity.GetUserId();
            Player player = db.Players.Where(x => x.AuthUserID.Equals(tempPlayer)).FirstOrDefault();

            if (player.PlayerID != game.Host)
            {
                return View("Error");
            }
            /////

            ViewBag.Host = new SelectList(db.Players, "PlayerID", "FirstName", game.Host);
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GameID,Name,Host,Active,StartDate,EndDate,Location,LocationCenterLong,LocatoinCenterLat,LocationRadius")] Game game)
        {
            string tempPlayer = User.Identity.GetUserId();
            Player player = db.Players.Where(x => x.AuthUserID.Equals(tempPlayer)).FirstOrDefault();
            if (ModelState.IsValid)
            {
                game.Host = player.PlayerID;
                db.Entry(game).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Dashboard");
            }
            ViewBag.Host = new SelectList(db.Players, "PlayerID", "FirstName", game.Host);
            return View(game);
        }

        // GET: Games/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            //prevents user deleting other user's game

elimination/Elimination/Elimination/Views/Games/Create.cshtml
@model Elimination.Models.Game

@{
    ViewBag.Title = "Create";
}

@if (Request.IsAuthenticated)
{

    <h2>Create</h2>

    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Game</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @id="datepicker" } })
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
}

else
{
    <h2>Please log in or register</h2>
}

elimination/Elimination/Elimination/Views/Games/Delete.cshtml
@model Elimination.Models.Game

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Game</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Player.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Player.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationCenterLong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationCenterLong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocatoinCenterLat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocatoinCenterLat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationRadius)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationRadius)
        </dd>

    </dl>

    <div>
        <label>Joined Players</label>
        <ul>
            @foreach (var PlayerID in Model.Players)
            {
                <li>@PlayerID.UserName</li>
            }
        </ul>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

elimination/Elimination/Elimination/Views/Games/Details.cshtml
@model Elimination.Models.Game

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Game</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Host
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Player.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationCenterLong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationCenterLong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocatoinCenterLat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocatoinCenterLat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationRadius)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationRadius)
        </dd>
    </dl>
</div>

@if (!ViewBag.Player.Equals("Host"))
{
    if (ViewBag.Player.Equals("AlreadyJoined"))
    {
        <button class="btn btn-default" onclick="if(confirm('Are you sure?')){location.href='@Url.Action("RemovePlayer", "Games", new { gameID = Model.GameID, playerID = ViewBag.playerID })'}">Leave Game</button>
    }
    else
    {
        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="JOIN" class="btn btn-default" id="join" />
                </div>
            </div>
        }
    }
} else
{
    <div>This is your game!</div>
}

<div>
    <label>Joined Players</label>
    <ul>
        @foreach (var player in Model.Players)
        {
            <li>@player.UserName</li>

            if (player.PlayerID.Equals(ViewBag.TargetID))
            {
             <li>test</li>
            }
        }
    </ul>
</div>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

elimination/Elimination/Elimination/Views/Games/HostDetails.cshtml
@model Elimination.Models.Game

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Game</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Host
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Player.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationCenterLong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationCenterLong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocatoinCenterLat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocatoinCenterLat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationRadius)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationRadius)
        </dd>
    </dl>
</div>

<div class="form-group">
    @Html.ActionLink("Add Players", "AddPlayers", new { id = Model.GameID }, new { @class = "btn btn-default" })
</div>
<table class="table table-container" id="game-players-table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Targets.FirstOrDefault().APlayer.UserName)
        </th>
        <th>
            Target
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var player in Model.Players)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => player.UserName)
            </td>
            <td>
                @{ var target = Model.Targets.FirstOrDefault(t => t.Player == player.PlayerID); }
                @if (target != null)
                {
                    @target.TargetPlayer.UserName;
                }
                else
                {
                    @:No Target
                }

            </td>
            <td>
                @if (Model.Active)
                {
                    <button class="sm-btn btn btn-default" onclick="location.href='@Url.Action("EliminatePlayer", "Games", new { gameID = Model.GameID, playerID = player.PlayerID })'">Eliminate</button>
                 }
                <button class="sm-btn btn btn-default" onclick="location.href='@Url.Action("RemovePlayer", "Games", new { gameID = Model.GameID, playerID = player.PlayerID })'">Remove</button>
            </td>
        </tr>
    }

</table>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.GameID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

elimination/Elimination/Elimination/Views/Games/Index.cshtml
@model IEnumerable<Elimination.Models.Game>

@{
    ViewBag.Title = "Index";
}

@if (Request.IsAuthenticated)
{

    <h2>Games</h2>
    <div>
       @using (Html.BeginForm("Index", "Games", FormMethod.Get))
       {

            <text>Upcoming Games Only: </text>@Html.CheckBox("inActive")
            <br />
            <b>Search By:</b>
            <br />
            @Html.RadioButton("searchBy", "Name") <text> Name </text>

            @Html.RadioButton("searchBy", "location")<text> Location </text>
            <br />
            <div class="row">
                <div class="col-md-3" >
                    @Html.TextBox("search", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3" style="margin-bottom: 10px;">
                    <input class="btn btn-default" type="submit" value="Search" />
                </div>
            </div>
       }
    </div>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table table-container">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Player.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Player.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.GameID, pid = item.Host })
                </td>
            </tr>
        }
    </table>
}
else
{
    <h2>Please log in or register</h2>
}

elimination/Elimination/Elimination/Views/Games/ViewPlayer.cshtml
@model Elimination.Models.Player

@{
    ViewBag.Title = "ViewPlayer";
}

<h2>ViewPlayer</h2>

<img src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(Model.Photo))"/>